### ISSUE TITLE
Компонент MainLayout

### ISSUE THREAD

**Issue by SleaD80** [SleaD80/Inbox#2]
Разработать компонент MainLayout.  
Если необходимо, можно добавить дополнительные слои.

- Должен включать компоненты TasksList, Head, Preview, TaskInfo 
- TasksList прокручивается, остальные закреплены
- Перемещаемая граница между компонентами

**Comment by SleaD80** [comment]
Исправить ошибки и предупреждения.
<img width="1277" alt="Screenshot 2023-08-21 at 10 41 37" src="https://github.com/SleaD80/Inbox/assets/11521250/c4659a31-5358-4f92-9ea4-de737b14fa9d">

**Comment by SleaD80** [comment]
Пакет column-resizer используется для изменения размеров элементов в таблицах. Его использование для цели изменения размера компонентов слоя не оправдано.
Посмотри другие пакеты, например re-resizable, react-resizable, react-resize-panel, etc.

**Comment by chdevel** [comment]
Привет.


  1.  Утверждение неверно. Таблицы в HTML — такой же способ управления расположением элементов, как и любой другой. В этой конкретной ситуации использование таблицы является оправданным.
  2.  re-resizable и react-resizable предназначены для других задач. react-resize-panel —трэш какой-то. column-resizer в условиях конкретной задачи является оптимальным, к тому же действительно грамотно написан, что немаловажно.

Смысла топтаться на месте, переделывая нормальный, работоспособный код с неясной мотивацией не вижу.


Best regards,
Michael Chernov,
Developer
TerraLink
+7 (495) 721-1-721 ext. 704



________________________________
От: SleaD80 ***@***.***>
Отправлено: 21 августа 2023 г. 11:07
Кому: SleaD80/Inbox
Копия: Chernov, Mikhail; Assign
Тема: Re: [SleaD80/Inbox] Компонент MainLayout (Issue #2)


Пакет column-resizer используется для изменения размеров элементов в таблицах. Его использование для цели изменения размера компонентов слоя не оправдано.
Посмотри другие пакеты, например re-resizable, react-resizable, react-resize-panel, etc.
